@startuml UseCase_BloodDonationSystem
skinparam style ubuntu
skinparam backgroundColor #FEFEFE
skinparam actorBackgroundColor #D0D0D0
skinparam usecaseBackgroundColor #AAFFAA

left to right direction

actor Donor
actor Staff
actor Admin

package "Blood Donation System" {
    usecase UC1  as "Login / Register"
    usecase UC2  as "Check Eligibility"
    usecase UC3  as "Book Appointment"
    usecase UC4  as "View Donation History"
    usecase UC5  as "Respond to Donation Request"
    usecase UC6  as "Manage Appointments"
    usecase UC7  as "Search Donors"
    usecase UC8  as "Send Donation Request"
    usecase UC9  as "Manage Blood Inventory"
    usecase UC10 as "Manage Accounts"
    usecase UC11 as "Logout"
}

Donor --> UC1
Donor --> UC2
Donor --> UC3
Donor --> UC4
Donor --> UC5
Donor --> UC11

Staff --> UC1
Staff --> UC6
Staff --> UC7
Staff --> UC8
Staff --> UC9
Staff --> UC11

Admin --> UC1
Admin --> UC10
Admin --> UC11
@enduml
